services:
  db:
    image: mysql:8.0
    container_name: pinter-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 7;wk[uJ8:4M5
      MYSQL_DATABASE: pinter
      MYSQL_USER: pinter_user
      MYSQL_PASSWORD: "7;wk[uJ8:4M5"
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ../pinter   
    container_name: pinter-backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/pinter
      SPRING_DATASOURCE_USERNAME: pinter_user
      SPRING_DATASOURCE_PASSWORD: "7;wk[uJ8:4M5"

  frontend:
    build:
      context: ../frontend   
    container_name: pinter-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  db_data: